@startuml
    (elindít) as x
    (boltot megnyit) as y
    (menüt megnyit) as z
    :játékos: -down- (nehézséget választ)
    (nehézséget választ) -down-> x : <<invokes>>
    x -down-> (kilép) : <<precedes>>
    x -down-> (időgyorsaságot állít) : <<precedes>>
    x -left-> y : <<precedes>>
    y -down-> (növényt vesz) : <<includes>>
    y -down-> (állatot vesz) : <<includes>>
    y -down-> (vizet vesz) : <<includes>>
    y -down-> (utat épít) : <<includes>>
    y -left-> (megfigyelő rendszert vesz) : <<includes>>
    (megfigyelő rendszert vesz) -down-> (fejleszt) : <<precedes>>
    x -right-> z : <<precedes>>

    z -down-> (belépődíjat változtat) : <<includes>>
    z -down-> (vadőrt megbíz) : <<includes>>
    (vadőrt megbíz) -down- (állatot kilövet) : <<precedes>>
    (vadőrt megbíz) -down- (orvvadászt kilövet) : <<extend>>
@enduml